APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:TYcCA+kH0PWDNQQngvoCv6qFwDwzIG2tQ045i8CDoFc=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
APP_MAINTENANCE_STORE=database

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=sqlsrv
DB_HOST=HIPNOS\MSSQLGEDIN
DB_PORT=54338
DB_DATABASE=SOLSERV
DB_USERNAME=gedinconn
DB_PASSWORD=Cotecmar2018

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

LDAP_HOST=artemisa.cotecmar.com 
LDAP_USERNAME=appda@cotecmar.com 
LDAP_PASSWORD=C0t3cm4r2019* 
LDAP_PORT=389 
LDAP_BASE_DN=dc=cotecmar,dc=com 
LDAP_TIMEOUT=5 
LDAP_SSL=false 
LDAP_TLS=false 
